// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAolV_Pu7p_-v8H__XZpL8cePWt2BWyKXc',
    appId: '1:787903299518:web:1dc58dc2d426b004cd03ef',
    messagingSenderId: '787903299518',
    projectId: 'integration-iot',
    authDomain: 'integration-iot.firebaseapp.com',
    databaseURL: 'https://integration-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'integration-iot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpMtoWq9G3slZGv7_Wq87wcQcjytAZXBA',
    appId: '1:787903299518:android:06c64339a0c90040cd03ef',
    messagingSenderId: '787903299518',
    projectId: 'integration-iot',
    databaseURL: 'https://integration-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'integration-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDAoY9FudaRxqTR1kL9pCABfdZyH7Vgx0',
    appId: '1:787903299518:ios:c5f6fe275388a5efcd03ef',
    messagingSenderId: '787903299518',
    projectId: 'integration-iot',
    databaseURL: 'https://integration-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'integration-iot.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );
}
